os:
  - linux
  - osx
language: c
addons:
  apt:
    packages:
    - libssl-dev
install:
- pip install --user azure-cli
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl; fi
before_script:
- wget https://qmcdn.blob.core.windows.net/imobiledevice/libplist-$TRAVIS_OS_NAME-1.13.0-97.tar.gz
- wget https://qmcdn.blob.core.windows.net/imobiledevice/libusbmuxd-$TRAVIS_OS_NAME-1.1.0-51.tar.gz
- mkdir $HOME/ext
- tar -xvzf libplist-$TRAVIS_OS_NAME-1.13.0-97.tar.gz -C $HOME/ext
- tar -xvzf libusbmuxd-$TRAVIS_OS_NAME-1.1.0-51.tar.gz -C $HOME/ext
- find $HOME/ext
- LC_CTYPE=C LANG=C find $HOME/ext/lib/pkgconfig/ -name '*.pc' -print0 | xargs -0 sed -i -e 's@/travis/out@/travis/ext@g'
- LC_CTYPE=C LANG=C find $HOME/ext/lib/ -name '*.la' -print0 | xargs -0 sed -i -e 's@/travis/out@/travis/ext@g'
script:
- export CFLAGS=-I$HOME/ext/include
- export PKG_CONFIG_PATH=$HOME/ext/lib/pkgconfig:$PKG_CONFIG_PATH
- export LDFLAGS=-L$HOME/ext/lib
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CFLAGS="$CFLAGS -I/usr/local/opt/openssl/include"; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export LDFLAGS="$LDFLAGS -L/usr/local/opt/openssl/lib"; fi
- pkg-config --print-errors --variable=prefix libplist
- pkg-config --print-errors --variable=prefix libusbmuxd
- ./autogen.sh --prefix=$HOME/out
- make
after_success:
- make install
- tar -zcvf libimobiledevice-$TRAVIS_OS_NAME.tar.gz -C $HOME/out .
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then az=$HOME/Library/Python/2.7/bin/az; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then az=$HOME/.local/bin/az; fi
- $az storage blob upload -f libimobiledevice-$TRAVIS_OS_NAME.tar.gz -c imobiledevice -n libimobiledevice-$TRAVIS_OS_NAME-1.2.1-$TRAVIS_BUILD_NUMBER.tar.gz
deploy:
  provider: releases
  file: libimobiledevice-$TRAVIS_OS_NAME.tar.gz
  skip_cleanup: true
  on:
    tags: true
